---
- hosts: windows
  
  tasks:
       - name: downloading winscp571setup.exe....
         win_copy:
               #src: //192.168.176.16/BuildShare/winscp571setup.exe
               src: \\192.168.176.16\BuildShare\winscp571setup.exe
               dest: E:\winscp571setup.exe
               remote_src: True

       - name: Installing.......
         raw: 'E:\winscp571setup.exe /silent'
         #raw: 
            #path: 'E:\winscp571setup.exe /Quiet /NoRestart /Full'
            #state: present       ccccc   kk
